### ISSUE TITLE
integration without node js

### ISSUE THREAD

**Issue by Omicron166** [thomax/ascii-animator#1]
hi @thomax 
I would like to use this library without using node
How can I make it browser compatible without using node js?

**Comment by thomax** [comment]
This library doesn't depend on anything else, so if you make a local copy of the compiled JS (found here https://github.com/thomax/ascii-animator/blob/master/lib/ascii-animator.js) and load that script like I do in the example HTML file (found here https://github.com/thomax/ascii-animator/blob/master/index.html) you should have something completely node-less running. From there you can wrap it however you want?

**Comment by Omicron166** [comment]
for some reason the html file doesn't work @thomax

**Comment by thomax** [comment]
@Omicron166yt I created an [html file](https://github.com/thomax/ascii-animator/blob/master/inlineJavascriptIncluded.html) with all the JS inline. Have a look at it, and revamp as you see fit?

**Comment by Omicron166** [comment]
problem solved, thank you very much
